version: '3.9'
services:
  etl:
    build:
      context: ./etl 
      dockerfile: Dockerfile
    container_name: disagro_hr_etl
    environment:
      BIGQUERY_PROJECT_ID: "bigquery-public-data"
      GOOGLE_APPLICATION_CREDENTIALS: /app/bigquery_key.json
    env_file:
      - .env.production
    restart: "no"
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: disagro_hr_api
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped